muttkraft/lib/muttkraft_web/router.ex
defmodule MuttkraftWeb.Router do
  use MuttkraftWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MuttkraftWeb do
    pipe_through [:browser, :maybe_authenticate_user]

    get "/", PageController, :index

    scope "/app", MuttkraftWeb do
      pipe_through [:authenticate_user]
      get "/hello", HelloController, :index
      get "/hello/:messenger", HelloController, :show
    end

    resources "/sessions", SessionController,
      only: [:new, :create, :delete],
      singleton: true

    resources "/villages", VillageController do
      get "buildings/:row/:column", BuildingController, :new
      resources "/buildings", BuildingController, except: [:new] do
        post "/units/:building_id/queue/:type/", UnitController, :create_in_queue, as: :create_in_queue
        delete "/units/:building_id/queue/:unit_id/", UnitController, :delete_from_queue, as: :delete_from_queue
      end
      resources "/units", UnitController
    end

    resources "/users", UserController do
      get "/become", UserController, :become
    end
  end

  defp maybe_authenticate_user(conn, _) do
    case get_session(conn, :user_id) do
      nil ->
        conn
      user_id -> 
        assign(conn, :current_user, Muttkraft.Accounts.get_user!(user_id))
    end
  end
  defp authenticate_user(conn, _) do
    case get_session(conn, :user_id) do
      nil ->
        conn
        |> Phoenix.Controller.put_flash(:error, "Login required")
        |> Phoenix.Controller.redirect(to: "/")
        |> halt()
      user_id ->
        assign(conn, :current_user, Muttkraft.Accounts.get_user!(user_id))
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", MuttkraftWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: MuttkraftWeb.Telemetry
    end
  end
end

muttkraft/lib/muttkraft/structures/building.ex
defmodule Muttkraft.Structures.Building do
  use Ecto.Schema
  import Ecto.Changeset

  schema "building" do
    field :column, :integer
    field :row, :integer
    field :type, Ecto.Enum, values: Enum.map(MuttkraftWeb.BuildingView.list_building_types, &(String.to_atom(&1)))

    belongs_to :village, Muttkraft.Village
    timestamps()
  end

  @doc false
  def changeset(building, attrs) do
    building
    |> cast(attrs, [:type, :row, :column, :village_id])
    |> validate_required([:type, :row, :column, :village_id])
    |> cast_assoc(:village)
  end
end

muttkraft/lib/muttkraft_web/controllers/building_controller.ex
defmodule MuttkraftWeb.BuildingController do
  use MuttkraftWeb, :controller

  alias Muttkraft.Structures
  alias Muttkraft.Structures.Building

  def index(conn, _params) do
    building = Structures.list_building()
    render(conn, "index.html", building: building)
  end

  def new(conn, %{"village_id" => village_id, "row" => row, "column" => column}) do
    village = Muttkraft.Map.get_village!(village_id)
    changeset = Structures.change_building(%Building{row: row, column: column})
    render(conn, "new.html", village: village, changeset: changeset)
  end

  def create(conn, %{"building" => building_params}) do
    case Structures.create_building(building_params) do
      {:ok, building} ->
        conn
        |> put_flash(:info, "Building created successfully.")
        |> redirect(to: Routes.village_path(conn, :show, building.village_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        village = Muttkraft.Map.get_village!(building_params["village_id"])
        render(conn, "new.html", village: village, changeset: changeset)
    end
  end

  def show(conn, %{"village_id" => village_id, "id" => id}) do
    village = Muttkraft.Map.get_village!(village_id)
    building = Structures.get_building!(id)
    Muttkraft.QueueCalculator.recalculate_queued(village)
    render(conn, "show.html", village: village, building: building)
  end

  def edit(conn, %{"village_id" => village_id, "id" => id}) do
    building = Structures.get_building!(id)
    changeset = Structures.change_building(building)
    render(conn, "edit.html", building: building, changeset: changeset)
  end

  def update(conn, %{"village_id" => village_id, "id" => id, "building" => building_params}) do
    building = Structures.get_building!(id)

    case Structures.update_building(building, building_params) do
      {:ok, building} ->
        conn
        |> put_flash(:info, "Building updated successfully.")
        |> redirect(to: Routes.building_path(conn, :show, building))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", building: building, changeset: changeset)
    end
  end

  def delete(conn, %{"village_id" => village_id, "id" => id}) do
    village = Muttkraft.Map.get_village!(village_id)
    building = Structures.get_building!(id)
    {:ok, _building} = Structures.delete_building(building)

    conn
    |> put_flash(:info, "Building deleted successfully.")
    |> redirect(to: Routes.village_path(conn, :show, village))
  end
end

muttkraft/lib/muttkraft_web/views/building_view.ex
defmodule MuttkraftWeb.BuildingView do
  use MuttkraftWeb, :view

  def list_building_types do
    ["town_hall", "sawmill", "shooting_range", "ore_pit", "gold_mine"]
  end

  def building_image_file(building_type) do
    file_name =
    case building_type do
      "town_hall" -> "town_hall.png"
      "sawmill" -> "sawmill.gif"
      "shooting_range" -> "shooting_range.png"
      "ore_pit" -> "ore_pit.gif"
      "gold_mine" -> "gold_mine.gif"
    end

    "/images/#{file_name}"
  end
end

muttkraft/lib/muttkraft_web/templates/building/_recruit.html.eex
<style>

 #unit-queue {
     display: flex;
     align-items: stretch;
     
 }

 #unit-queue img {
     transform: scaleX(-1);
 }

 #unit-queue .button {
     height: 1.7rem;
     line-height: 1.7rem;
     background-color: darkred;
     margin: 0.2rem;
     border-color: darkred;
     padding-right: 0.5rem;
     padding-left: 0.5rem;
 }

 #unit-queue button.first-item {
     align-self: center;
 }

 #unit-queue .bottom-unit-preview.first {
     display: grid;
     align-items: center;
     grid-template-columns: 2fr 1fr;

 }

 #unit-queue .bottom-unit-preview  {
     display: grid;
     align-items: center;
     grid-template-columns: 1fr  1fr 1fr;
 }


 #unit-queue .outer-progress {

     border: 1px solid black;
     border-radius: 5px;
     background-color: black;
     height: 6px;
 }

 #unit-queue .inner-progress {
     background-color: #b1d443;
     border-radius: 5px;
     height: 100%;
 }

 #unit-buy {
     display: flex;
     align-items: stretch;
 }

 .unit-preview {
     display: flex;
     flex-direction: column;
 }

 .unit-preview .button {
     height: 1.7rem;
     line-height: 1.7rem;
     align-self: center;
 }

 .unit-img-wrapper {
     width: 90px;
     height: 95px;

     display: flex;
     justify-content: center;
     align-items: flex-end;
     
 }

 .unit-img-wrapper img {
     image-rendering: pixelated;
     margin-bottom: 5px;
 }

</style>

<h2>Train</h2>
<div id="unit-buy">
    <%= for name <- ["goblin", "orc", "ogre",  "peasant", "pikerman", "halfling", "boar", "hydra"] do %>
        <div class="unit-preview">
            <div class="unit-img-wrapper">
                <img src="<%= Routes.static_path(@conn, "/images/units/#{name}.png") %>"/>
            </div>

            <%= if match?({:ok, _ }, Muttkraft.QueueCalculator.can_buy?(@village, @resource_pile, name)) do %>
                <%= link to: Routes.village_building_create_in_queue_path(@conn, :create_in_queue, @village.id, @building.id, name), method: :create_in_queue, class: "button #{if name == "hydra.png" || name == "boar.png", do: "disabled"}" do %>
                    +1
                <% end %>
            <% else %>
                <button class="button" disabled> +1</button>
            <% end %>
        </div>
    <% end %>
</div>

<h2>Queue</h2>

<div id="unit-queue">
    <%= for {unit, i} <- Muttkraft.Army.get_queued_units_in_village(@village.id) |> Muttkraft.Repo.all |> Enum.with_index do %>
        <div class="unit-preview">
            <div class="unit-img-wrapper">
                <img src="<%= Routes.static_path(@conn, "/images/units/#{unit.type}.png") %>"/>
            </div>

            <div class="bottom-unit-preview <%= if i == 0, do: "first" %>">
                <%= if i == 0 do %>
                    <div
                        class="outer-progress"
                        data-controller="recruit-queue"
                        data-recruit-queue-max-value="<%= Muttkraft.QueueCalculator.unit_to_queue_time(unit.type) %>"
                        data-recruit-queue-current-value="<%= unit.queue_time %>"
                        >
                        <div class="inner-progress" style="width: <%= unit.queue_time / Muttkraft.QueueCalculator.unit_to_queue_time(unit.type) * 100 %>%" %"
                             data-recruit-queue-target="innerProgressBar"
                        ></div>
                    </div>
                <% else %>
                    <div></div>
                <% end %>

                <%= link to: Routes.village_building_delete_from_queue_path(@conn, :delete_from_queue, @village.id, @building.id, unit.id),
                method: :delete, class: "button #{if i == 0, do: "first-item"}" do %>
                    X
                <% end %>
            </div>
            
        </div>
    <% end %>
</div>

<h2>Your current units</h2>
<div>
    <%= for _ <- 1..5 do %>
        <img src="<%= Routes.static_path(@conn, "/images/units/goblin_mini.png") %>"/>
    <% end %>
    <img src="<%= Routes.static_path(@conn, "/images/units/orc_mini.png") %>"/>
</div>


<div data-controller="page">
    <input data-target="page.myInput" type="text">
    <button data-action="click->page#alertText">Click Here</button>
</div>

muttkraft/lib/muttkraft_web/templates/building/edit.html.eex
<h1>Edit Building</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.building_path(@conn, :update, @building)) %>

<span><%= link "Back", to: Routes.building_path(@conn, :index) %></span>

muttkraft/lib/muttkraft_web/templates/building/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
        <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :type %>
  <%= select f, :type, ["Townhall": "town_hall",
  "Shooting Range": "shooting_range", "Sawmill": "sawmill", "Ore Pit": "ore_pit", "Gold mine": "gold_mine"] %>
  <%= error_tag f, :type %>

  <%= hidden_input f, :village_id, value: @village.id%>
  <%= error_tag f, :village_id %>

  <%= hidden_input f, :row %>
  <%= error_tag f, :row %>


  <%= hidden_input f, :column %>
  <%= error_tag f, :column %>


  

  <div>
    <%= submit "Save" %>
  </div>
<% end %>


<div x-data="{ open: false }">
    <button @click="open = true">Open Dropdown</button>

    <ul
        x-show.transition.duration.2000ms="open"
        @click.away="open = false"
    >
        Dropdown Body
    </ul>
</div>


<div x-data="{ tab: 'foo' }">
    <button :class="{ 'active': tab === 'foo' }" @click="tab = 'foo'">Foo</button>
    <button :class="{ 'active': tab === 'bar' }" @click="tab = 'bar'">Bar</button>

    <div x-show.transition.duration.2000ms="tab === 'foo'" >Tab Foo</div>
    <div x-show.transition.duration.2000ms="tab === 'bar'">Tab Bar</div>
</div>

<div x-show.transition="open">
    These contents will be transitioned in and out.
</div>

muttkraft/lib/muttkraft_web/templates/building/index.html.eex
<h1>Listing Building</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Row</th>
      <th>Column</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for building <- @building do %>
    <tr>
      <td><%= building.type %></td>
      <td><%= building.row %></td>
      <td><%= building.column %></td>

      <td>
        <span><%= link "Show", to: Routes.building_path(@conn, :show, building) %></span>
        <span><%= link "Edit", to: Routes.building_path(@conn, :edit, building) %></span>
        <span><%= link "Delete", to: Routes.building_path(@conn, :delete, building), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Building", to: Routes.building_path(@conn, :new) %></span>

muttkraft/lib/muttkraft_web/templates/building/new.html.eex
<h1>New Building</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.village_building_path(@conn, :create, @village.id)) %>

<span><%= link "Back", to: Routes.village_path(@conn, :show, @village.id) %></span>

muttkraft/lib/muttkraft_web/templates/building/show.html.eex
<h1><%= @building.type %></h1>

<%= if @building.type == :shooting_range do %>
  <%= render "_recruit.html", conn: @conn, village: @village, building: @building, resource_pile: @village.resource_pile %>
   <% else %>
    <ul>
        <li>
            <strong>Row:</strong>
            <%= @building.row %>
        </li>

        <li>
            <strong>Column:</strong>
            <%= @building.column %>
        </li>

    </ul>
<% end %>

<span><%= link "Delete", to: Routes.village_building_path(@conn, :delete, @village, @building), method: :delete, data: [confirm: "Are you sure?"] %></span>
<span><%= link "Edit", to: Routes.village_building_path(@conn, :edit, @village, @building) %></span>
<span><%= link "Back", to: Routes.village_path(@conn, :show, @village) %></span>